import { Check, Cloud, Download, HardDrive, Play, Sparkles } from "lucide-react";
import { currentPlan, currentStatus, plans, usage, usagePercent, usageStatus } from "../data/plans";

const icons = { downloads: Download, previews: Play, storage: HardDrive, connections: Cloud } as const;
export function Plans() {
  const active = plans.find((plan) => plan.key === currentPlan)!;
  return <div className="page-stack plans-page">
    <header className="page-header"><div><p className="eyebrow">Workspace / subscription</p><h1>Plans & Subscription</h1><p className="description">Control local de entitlements para tu workspace creativo.</p></div><span className="badge demo">DEMO · SIN PAGOS</span></header>
    <section className="panel current-plan"><div><p className="eyebrow">Plan actual</p><h2>{active.name} <span className="badge cyan">{currentStatus}</span></h2><p className="description">Trial local activo hasta el 14 de septiembre. No se requiere tarjeta.</p></div><button className="button" type="button" onClick={() => undefined}>Gestionar demo</button></section>
    <section><div className="section-heading"><div><p className="eyebrow">Usage snapshot</p><h2>Tu consumo este periodo</h2></div><small>Se reinicia de forma simulada</small></div><div className="usage-grid">{usage.map((item) => { const Icon = icons[item.key]; const status = usageStatus(item); return <article className="panel usage-card" key={item.key}><Icon size={18} aria-hidden="true" /><strong>{item.used} <small>/ {item.limit} {item.unit}</small></strong><span>{item.label}</span><div className="usage-bar" role="progressbar" aria-label={item.label} aria-valuenow={item.used} aria-valuemin={0} aria-valuemax={item.limit}><i className={status} style={{ width: `${usagePercent(item)}%` }} /></div><em>{status === "attention" ? "Cerca del límite" : status === "full" ? "Límite alcanzado" : "Dentro del plan"}</em></article>; })}</div></section>
    <section><div className="section-heading"><div><p className="eyebrow">Compare</p><h2>Planes mock</h2></div></div><div className="plans-grid">{plans.map((plan) => <article className={`panel plan-card ${plan.featured ? "featured" : ""}`} key={plan.key}>{plan.featured && <span className="plan-ribbon"><Sparkles size={12} /> Recomendado</span>}<h2>{plan.name}</h2><p className="description">{plan.description}</p><strong className="plan-price">{plan.price}<small>/mes</small></strong><ul>{Object.entries(plan.limits).map(([key, value]) => <li key={key}><Check size={15} /> {value} {key === "storage" ? "GB storage" : key === "connections" ? "conexiones cloud" : key === "previews" ? "min previews" : "descargas"}</li>)}</ul><button className={`button ${plan.key === currentPlan ? "ghost" : ""}`} type="button" onClick={() => undefined}>{plan.key === currentPlan ? "Plan actual" : plan.key === "free" ? "Downgrade demo" : "Upgrade demo"}</button></article>)}</div></section>
    <p className="demo-note">Las acciones son visuales. El plan, usage y límites son mock data; la autorización y los entitlements reales deberán calcularse server-side.</p>
  </div>;
}
