import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { X } from "lucide-react";
import type { Project, ProjectStatus } from "../types";

const projectStatuses: ProjectStatus[] = ["Draft", "Working", "Demo", "Ready", "Released"];
const projectColors = ["#35d0ba", "#8c7bff", "#e5a85b", "#f0789a", "#4ca6d8"];
type ProjectForm = { name: string; genre: string; bpm: string; key: string; status: ProjectStatus };

export function ProjectModal({ project, onClose, onSave }: { project?: Project; onClose: () => void; onSave: (project: Project) => void }) {
  const [form, setForm] = useState<ProjectForm>({ name: project?.name ?? "", genre: project?.genre ?? "", bpm: String(project?.bpm ?? 120), key: project?.key ?? "", status: project?.status ?? "Draft" });
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]);
  const errors = { name: !form.name.trim() ? "Name is required." : "", genre: !form.genre.trim() ? "Genre is required." : "", bpm: !/^\d+$/.test(form.bpm) || Number(form.bpm) < 40 || Number(form.bpm) > 240 ? "Use a BPM from 40 to 240." : "", key: !form.key.trim() ? "Key is required." : "" };
  const update = (change: Partial<ProjectForm>) => setForm((current) => ({ ...current, ...change }));
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); if (Object.values(errors).some(Boolean)) return; onSave({ id: project?.id ?? `local-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, name: form.name.trim(), genre: form.genre.trim(), bpm: Number(form.bpm), key: form.key.trim(), modified: "Just now", status: form.status, color: project?.color ?? projectColors[Date.now() % projectColors.length], tracks: project?.tracks ?? 0, cover: project?.cover }); };
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><div className="modal-heading"><div><p className="eyebrow">Local project</p><h2 id="project-modal-title">{project ? "Edit project" : "New project"}</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label="Close project dialog"><X size={18} aria-hidden="true" /></button></div><form onSubmit={submit} noValidate><div className="form-grid">{([['name','Name','e.g. Midnight Theory'],['genre','Genre','e.g. Dark Trap'],['key','Key','e.g. F minor']] as const).map(([field,label,placeholder])=><label key={field}>{label}<input autoFocus={field === 'name'} value={form[field]} onChange={(event) => update({ [field]: event.target.value })} aria-invalid={submitted && Boolean(errors[field])} placeholder={placeholder}/>{submitted && errors[field] && <small className="field-error">{errors[field]}</small>}</label>)}<label>BPM<input type="number" min="40" max="240" value={form.bpm} onChange={(event) => update({ bpm: event.target.value })} aria-invalid={submitted && Boolean(errors.bpm)}/>{submitted && errors.bpm && <small className="field-error">{errors.bpm}</small>}</label></div><label className="modal-status">Status<select value={form.status} onChange={(event) => update({ status: event.target.value as ProjectStatus })}>{projectStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button type="submit" className="button">{project ? "Save changes" : "Create project"}</button></div></form></section></div>;
}
